/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.NetworkTokenTokenizationResultCode;
import com.konfigthis.client.model.PaymentsBankCardBase;
import com.konfigthis.client.model.PaymentsNetworkTokenSchemes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NetworkTokenTokenizationResult
 */
public class NetworkTokenTokenizationResultTest {
    private final NetworkTokenTokenizationResult model = new NetworkTokenTokenizationResult();

    /**
     * Model tests for NetworkTokenTokenizationResult
     */
    @Test
    public void testNetworkTokenTokenizationResult() {
        // TODO: test NetworkTokenTokenizationResult
    }

    /**
     * Test the property 'resultCode'
     */
    @Test
    public void resultCodeTest() {
        // TODO: test resultCode
    }

    /**
     * Test the property 'brand'
     */
    @Test
    public void brandTest() {
        // TODO: test brand
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'tokenizedCard'
     */
    @Test
    public void tokenizedCardTest() {
        // TODO: test tokenizedCard
    }

}
