/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentsResult
 */
public class PaymentsResultTest {
    /**
     * Model tests for PaymentsResult
     */
    @Test
    public void testPaymentsResult() {
        // TODO: test PaymentsResult
    }

}
