/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PaymentsCurrencyCode;
import com.konfigthis.client.model.PaymentsOperation;
import com.konfigthis.client.model.PaymentsResult;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentsOperationResult
 */
public class PaymentsOperationResultTest {
    private final PaymentsOperationResult model = new PaymentsOperationResult();

    /**
     * Model tests for PaymentsOperationResult
     */
    @Test
    public void testPaymentsOperationResult() {
        // TODO: test PaymentsOperationResult
    }

    /**
     * Test the property 'authorizationCode'
     */
    @Test
    public void authorizationCodeTest() {
        // TODO: test authorizationCode
    }

    /**
     * Test the property 'operationType'
     */
    @Test
    public void operationTypeTest() {
        // TODO: test operationType
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'operationResultCode'
     */
    @Test
    public void operationResultCodeTest() {
        // TODO: test operationResultCode
    }

    /**
     * Test the property 'operationResultDescription'
     */
    @Test
    public void operationResultDescriptionTest() {
        // TODO: test operationResultDescription
    }

    /**
     * Test the property 'customGatewayResponse'
     */
    @Test
    public void customGatewayResponseTest() {
        // TODO: test customGatewayResponse
    }

    /**
     * Test the property 'gatewayName'
     */
    @Test
    public void gatewayNameTest() {
        // TODO: test gatewayName
    }

    /**
     * Test the property 'gatewayReference'
     */
    @Test
    public void gatewayReferenceTest() {
        // TODO: test gatewayReference
    }

    /**
     * Test the property 'gatewayResultCode'
     */
    @Test
    public void gatewayResultCodeTest() {
        // TODO: test gatewayResultCode
    }

    /**
     * Test the property 'gatewayResultDescription'
     */
    @Test
    public void gatewayResultDescriptionTest() {
        // TODO: test gatewayResultDescription
    }

    /**
     * Test the property 'gatewayResultSubCode'
     */
    @Test
    public void gatewayResultSubCodeTest() {
        // TODO: test gatewayResultSubCode
    }

    /**
     * Test the property 'gatewayResultSubDescription'
     */
    @Test
    public void gatewayResultSubDescriptionTest() {
        // TODO: test gatewayResultSubDescription
    }

    /**
     * Test the property 'gatewayToken'
     */
    @Test
    public void gatewayTokenTest() {
        // TODO: test gatewayToken
    }

}
