/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentsBankCardBase
 */
public class PaymentsBankCardBaseTest {
    private final PaymentsBankCardBase model = new PaymentsBankCardBase();

    /**
     * Model tests for PaymentsBankCardBase
     */
    @Test
    public void testPaymentsBankCardBase() {
        // TODO: test PaymentsBankCardBase
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'expirationMonth'
     */
    @Test
    public void expirationMonthTest() {
        // TODO: test expirationMonth
    }

    /**
     * Test the property 'expirationYear'
     */
    @Test
    public void expirationYearTest() {
        // TODO: test expirationYear
    }

}
