/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PaymentsCurrencyCode;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentsMoney
 */
public class PaymentsMoneyTest {
    private final PaymentsMoney model = new PaymentsMoney();

    /**
     * Model tests for PaymentsMoney
     */
    @Test
    public void testPaymentsMoney() {
        // TODO: test PaymentsMoney
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'iso4217CurrencyNumber'
     */
    @Test
    public void iso4217CurrencyNumberTest() {
        // TODO: test iso4217CurrencyNumber
    }

    /**
     * Test the property 'amountInLargestUnits'
     */
    @Test
    public void amountInLargestUnitsTest() {
        // TODO: test amountInLargestUnits
    }

    /**
     * Test the property 'formattedAmount'
     */
    @Test
    public void formattedAmountTest() {
        // TODO: test formattedAmount
    }

}
