/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PaymentsCardTypes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentsBankCard
 */
public class PaymentsBankCardTest {
    private final PaymentsBankCard model = new PaymentsBankCard();

    /**
     * Model tests for PaymentsBankCard
     */
    @Test
    public void testPaymentsBankCard() {
        // TODO: test PaymentsBankCard
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'nameOnCard'
     */
    @Test
    public void nameOnCardTest() {
        // TODO: test nameOnCard
    }

    /**
     * Test the property 'issueNumber'
     */
    @Test
    public void issueNumberTest() {
        // TODO: test issueNumber
    }

    /**
     * Test the property 'ownerId'
     */
    @Test
    public void ownerIdTest() {
        // TODO: test ownerId
    }

    /**
     * Test the property 'securityCode'
     */
    @Test
    public void securityCodeTest() {
        // TODO: test securityCode
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'expirationMonth'
     */
    @Test
    public void expirationMonthTest() {
        // TODO: test expirationMonth
    }

    /**
     * Test the property 'expirationYear'
     */
    @Test
    public void expirationYearTest() {
        // TODO: test expirationYear
    }

}
