/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PayToolsBlAuthenticationChargePresetData;
import com.konfigthis.client.model.PayToolsBlAuthenticationThreeDsPresetData;
import com.konfigthis.client.model.PayToolsBlAuthenticationTokenizationAction;
import com.konfigthis.client.model.PayToolsSharedEnumsPerform3ds;
import com.konfigthis.client.model.PaymentsChargeRequest;
import com.konfigthis.client.model.PaymentsOperationResult;
import com.konfigthis.client.model.PciBookingIINLookupLibraryCardValidationRequest;
import com.konfigthis.client.model.PciBookingIINLookupLibraryCardValidationResult;
import com.konfigthis.client.model.PciBookingIINLookupLibraryRiskLevel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PayToolsBlAuthenticationSignedData
 */
public class PayToolsBlAuthenticationSignedDataTest {
    private final PayToolsBlAuthenticationSignedData model = new PayToolsBlAuthenticationSignedData();

    /**
     * Model tests for PayToolsBlAuthenticationSignedData
     */
    @Test
    public void testPayToolsBlAuthenticationSignedData() {
        // TODO: test PayToolsBlAuthenticationSignedData
    }

    /**
     * Test the property 'vldRq'
     */
    @Test
    public void vldRqTest() {
        // TODO: test vldRq
    }

    /**
     * Test the property 'vldRs'
     */
    @Test
    public void vldRsTest() {
        // TODO: test vldRs
    }

    /**
     * Test the property 'crgRq'
     */
    @Test
    public void crgRqTest() {
        // TODO: test crgRq
    }

    /**
     * Test the property 'crgRs'
     */
    @Test
    public void crgRsTest() {
        // TODO: test crgRs
    }

    /**
     * Test the property 'tknRs'
     */
    @Test
    public void tknRsTest() {
        // TODO: test tknRs
    }

    /**
     * Test the property '_3dsD'
     */
    @Test
    public void _3dsDTest() {
        // TODO: test _3dsD
    }

    /**
     * Test the property 'vld'
     */
    @Test
    public void vldTest() {
        // TODO: test vld
    }

    /**
     * Test the property '_3ds'
     */
    @Test
    public void _3dsTest() {
        // TODO: test _3ds
    }

    /**
     * Test the property 'crg'
     */
    @Test
    public void crgTest() {
        // TODO: test crg
    }

    /**
     * Test the property 'tkn'
     */
    @Test
    public void tknTest() {
        // TODO: test tkn
    }

    /**
     * Test the property 'crgD'
     */
    @Test
    public void crgDTest() {
        // TODO: test crgD
    }

}
