/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PayToolsApiModelsTopBrands
 */
public class PayToolsApiModelsTopBrandsTest {
    private final PayToolsApiModelsTopBrands model = new PayToolsApiModelsTopBrands();

    /**
     * Model tests for PayToolsApiModelsTopBrands
     */
    @Test
    public void testPayToolsApiModelsTopBrands() {
        // TODO: test PayToolsApiModelsTopBrands
    }

    /**
     * Test the property 'prefixes'
     */
    @Test
    public void prefixesTest() {
        // TODO: test prefixes
    }

    /**
     * Test the property 'logos'
     */
    @Test
    public void logosTest() {
        // TODO: test logos
    }

}
