/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PaymentsCardTypes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PayToolsSharedModelsCardStoredCard
 */
public class PayToolsSharedModelsCardStoredCardTest {
    private final PayToolsSharedModelsCardStoredCard model = new PayToolsSharedModelsCardStoredCard();

    /**
     * Model tests for PayToolsSharedModelsCardStoredCard
     */
    @Test
    public void testPayToolsSharedModelsCardStoredCard() {
        // TODO: test PayToolsSharedModelsCardStoredCard
    }

    /**
     * Test the property 'cardToken'
     */
    @Test
    public void cardTokenTest() {
        // TODO: test cardToken
    }

    /**
     * Test the property 'expirationYear'
     */
    @Test
    public void expirationYearTest() {
        // TODO: test expirationYear
    }

    /**
     * Test the property 'expirationMonth'
     */
    @Test
    public void expirationMonthTest() {
        // TODO: test expirationMonth
    }

    /**
     * Test the property 'cardType'
     */
    @Test
    public void cardTypeTest() {
        // TODO: test cardType
    }

    /**
     * Test the property 'cardHolderName'
     */
    @Test
    public void cardHolderNameTest() {
        // TODO: test cardHolderName
    }

}
