/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PaymentsCardTypes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PayToolsDalEntitiesThreeDsBrand
 */
public class PayToolsDalEntitiesThreeDsBrandTest {
    private final PayToolsDalEntitiesThreeDsBrand model = new PayToolsDalEntitiesThreeDsBrand();

    /**
     * Model tests for PayToolsDalEntitiesThreeDsBrand
     */
    @Test
    public void testPayToolsDalEntitiesThreeDsBrand() {
        // TODO: test PayToolsDalEntitiesThreeDsBrand
    }

    /**
     * Test the property 'brand'
     */
    @Test
    public void brandTest() {
        // TODO: test brand
    }

    /**
     * Test the property 'bin'
     */
    @Test
    public void binTest() {
        // TODO: test bin
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    public void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'mcc'
     */
    @Test
    public void mccTest() {
        // TODO: test mcc
    }

}
