/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PciBookingIINLookupLibraryCardValidationRequest
 */
public class PciBookingIINLookupLibraryCardValidationRequestTest {
    private final PciBookingIINLookupLibraryCardValidationRequest model = new PciBookingIINLookupLibraryCardValidationRequest();

    /**
     * Model tests for PciBookingIINLookupLibraryCardValidationRequest
     */
    @Test
    public void testPciBookingIINLookupLibraryCardValidationRequest() {
        // TODO: test PciBookingIINLookupLibraryCardValidationRequest
    }

    /**
     * Test the property 'iin'
     */
    @Test
    public void iinTest() {
        // TODO: test iin
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'stateProvince'
     */
    @Test
    public void stateProvinceTest() {
        // TODO: test stateProvince
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'clientIPAddress'
     */
    @Test
    public void clientIPAddressTest() {
        // TODO: test clientIPAddress
    }

}
