/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Payments.Result
 */
@JsonAdapter(PaymentsResult.Adapter.class)public enum PaymentsResult {
  
  SUCCESS("Success"),
  
  ACCEPTED("Accepted"),
  
  REJECTED("Rejected"),
  
  TEMPORARYFAILURE("TemporaryFailure"),
  
  FATALFAILURE("FatalFailure"),
  
  NOTIMPLEMENTED("NotImplemented");

  private String value;

  PaymentsResult(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PaymentsResult fromValue(String value) {
    for (PaymentsResult b : PaymentsResult.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PaymentsResult> {
    @Override
    public void write(final JsonWriter jsonWriter, final PaymentsResult enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PaymentsResult read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PaymentsResult.fromValue(value);
    }
  }
}

