/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Payments.NetworkTokenSchemes
 */
@JsonAdapter(PaymentsNetworkTokenSchemes.Adapter.class)public enum PaymentsNetworkTokenSchemes {
  
  VISA("Visa"),
  
  MASTERCARD("MasterCard"),
  
  AMEX("Amex");

  private String value;

  PaymentsNetworkTokenSchemes(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PaymentsNetworkTokenSchemes fromValue(String value) {
    for (PaymentsNetworkTokenSchemes b : PaymentsNetworkTokenSchemes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PaymentsNetworkTokenSchemes> {
    @Override
    public void write(final JsonWriter jsonWriter, final PaymentsNetworkTokenSchemes enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PaymentsNetworkTokenSchemes read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PaymentsNetworkTokenSchemes.fromValue(value);
    }
  }
}

