/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PayToolsApiModelsIinData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Luhn Check Results with IIn Data
 */
@ApiModel(description = "Luhn Check Results with IIn Data")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PayToolsApiModelsLuhnCheckResultsWithIinData {
  public static final String SERIALIZED_NAME_IIN_DATA = "iinData";
  @SerializedName(SERIALIZED_NAME_IIN_DATA)
  private PayToolsApiModelsIinData iinData;

  public static final String SERIALIZED_NAME_LUHN_VALID = "luhnValid";
  @SerializedName(SERIALIZED_NAME_LUHN_VALID)
  private Boolean luhnValid;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private String error;

  public PayToolsApiModelsLuhnCheckResultsWithIinData() {
  }

  public PayToolsApiModelsLuhnCheckResultsWithIinData iinData(PayToolsApiModelsIinData iinData) {
    
    
    
    
    this.iinData = iinData;
    return this;
  }

   /**
   * Get iinData
   * @return iinData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PayToolsApiModelsIinData getIinData() {
    return iinData;
  }


  public void setIinData(PayToolsApiModelsIinData iinData) {
    
    
    
    this.iinData = iinData;
  }


  public PayToolsApiModelsLuhnCheckResultsWithIinData luhnValid(Boolean luhnValid) {
    
    
    
    
    this.luhnValid = luhnValid;
    return this;
  }

   /**
   * Indicates a successful luhn check
   * @return luhnValid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates a successful luhn check")

  public Boolean getLuhnValid() {
    return luhnValid;
  }


  public void setLuhnValid(Boolean luhnValid) {
    
    
    
    this.luhnValid = luhnValid;
  }


  public PayToolsApiModelsLuhnCheckResultsWithIinData error(String error) {
    
    
    
    
    this.error = error;
    return this;
  }

   /**
   * Error description
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Error description")

  public String getError() {
    return error;
  }


  public void setError(String error) {
    
    
    
    this.error = error;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PayToolsApiModelsLuhnCheckResultsWithIinData instance itself
   */
  public PayToolsApiModelsLuhnCheckResultsWithIinData putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayToolsApiModelsLuhnCheckResultsWithIinData payToolsApiModelsLuhnCheckResultsWithIinData = (PayToolsApiModelsLuhnCheckResultsWithIinData) o;
    return Objects.equals(this.iinData, payToolsApiModelsLuhnCheckResultsWithIinData.iinData) &&
        Objects.equals(this.luhnValid, payToolsApiModelsLuhnCheckResultsWithIinData.luhnValid) &&
        Objects.equals(this.error, payToolsApiModelsLuhnCheckResultsWithIinData.error)&&
        Objects.equals(this.additionalProperties, payToolsApiModelsLuhnCheckResultsWithIinData.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(iinData, luhnValid, error, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayToolsApiModelsLuhnCheckResultsWithIinData {\n");
    sb.append("    iinData: ").append(toIndentedString(iinData)).append("\n");
    sb.append("    luhnValid: ").append(toIndentedString(luhnValid)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("iinData");
    openapiFields.add("luhnValid");
    openapiFields.add("error");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PayToolsApiModelsLuhnCheckResultsWithIinData
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PayToolsApiModelsLuhnCheckResultsWithIinData.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PayToolsApiModelsLuhnCheckResultsWithIinData is not found in the empty JSON string", PayToolsApiModelsLuhnCheckResultsWithIinData.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `iinData`
      if (jsonObj.get("iinData") != null && !jsonObj.get("iinData").isJsonNull()) {
        PayToolsApiModelsIinData.validateJsonObject(jsonObj.getAsJsonObject("iinData"));
      }
      if (!jsonObj.get("error").isJsonNull() && (jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) && !jsonObj.get("error").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `error` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PayToolsApiModelsLuhnCheckResultsWithIinData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PayToolsApiModelsLuhnCheckResultsWithIinData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PayToolsApiModelsLuhnCheckResultsWithIinData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PayToolsApiModelsLuhnCheckResultsWithIinData.class));

       return (TypeAdapter<T>) new TypeAdapter<PayToolsApiModelsLuhnCheckResultsWithIinData>() {
           @Override
           public void write(JsonWriter out, PayToolsApiModelsLuhnCheckResultsWithIinData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PayToolsApiModelsLuhnCheckResultsWithIinData read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PayToolsApiModelsLuhnCheckResultsWithIinData instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PayToolsApiModelsLuhnCheckResultsWithIinData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PayToolsApiModelsLuhnCheckResultsWithIinData
  * @throws IOException if the JSON string is invalid with respect to PayToolsApiModelsLuhnCheckResultsWithIinData
  */
  public static PayToolsApiModelsLuhnCheckResultsWithIinData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PayToolsApiModelsLuhnCheckResultsWithIinData.class);
  }

 /**
  * Convert an instance of PayToolsApiModelsLuhnCheckResultsWithIinData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

