/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Base model for card with Security code
 */
@ApiModel(description = "Base model for card with Security code")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PayToolsApiModelsCardBaseWithSecurityCode {
  public static final String SERIALIZED_NAME_CVV = "cvv";
  @SerializedName(SERIALIZED_NAME_CVV)
  private String cvv;

  public static final String SERIALIZED_NAME_CARD_NUMBER = "cardNumber";
  @SerializedName(SERIALIZED_NAME_CARD_NUMBER)
  private String cardNumber;

  public static final String SERIALIZED_NAME_EXPIRATION_YEAR = "expirationYear";
  @SerializedName(SERIALIZED_NAME_EXPIRATION_YEAR)
  private Integer expirationYear;

  public static final String SERIALIZED_NAME_EXPIRATION_MONTH = "expirationMonth";
  @SerializedName(SERIALIZED_NAME_EXPIRATION_MONTH)
  private Integer expirationMonth;

  public PayToolsApiModelsCardBaseWithSecurityCode() {
  }

  public PayToolsApiModelsCardBaseWithSecurityCode cvv(String cvv) {
    
    
    
    
    this.cvv = cvv;
    return this;
  }

   /**
   * Card security code (digits on back of card)
   * @return cvv
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Card security code (digits on back of card)")

  public String getCvv() {
    return cvv;
  }


  public void setCvv(String cvv) {
    
    
    
    this.cvv = cvv;
  }


  public PayToolsApiModelsCardBaseWithSecurityCode cardNumber(String cardNumber) {
    
    
    if (cardNumber != null && cardNumber.length() < 1) {
      throw new IllegalArgumentException("Invalid value for cardNumber. Length must be greater than or equal to 1.");
    }
    
    this.cardNumber = cardNumber;
    return this;
  }

   /**
   * Card number (PAN) or a Reference to a Tokenized string. A Token should be referenced in the format @TOKEN, e.g \&quot;@nQGywsQE9gbURtrXEjTZwtWqeMdK9nsO\&quot;
   * @return cardNumber
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Card number (PAN) or a Reference to a Tokenized string. A Token should be referenced in the format @TOKEN, e.g \"@nQGywsQE9gbURtrXEjTZwtWqeMdK9nsO\"")

  public String getCardNumber() {
    return cardNumber;
  }


  public void setCardNumber(String cardNumber) {
    
    
    if (cardNumber != null && cardNumber.length() < 1) {
      throw new IllegalArgumentException("Invalid value for cardNumber. Length must be greater than or equal to 1.");
    }
    this.cardNumber = cardNumber;
  }


  public PayToolsApiModelsCardBaseWithSecurityCode expirationYear(Integer expirationYear) {
    
    
    
    
    this.expirationYear = expirationYear;
    return this;
  }

   /**
   * Expiration year
   * @return expirationYear
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Expiration year")

  public Integer getExpirationYear() {
    return expirationYear;
  }


  public void setExpirationYear(Integer expirationYear) {
    
    
    
    this.expirationYear = expirationYear;
  }


  public PayToolsApiModelsCardBaseWithSecurityCode expirationMonth(Integer expirationMonth) {
    if (expirationMonth != null && expirationMonth < 1) {
      throw new IllegalArgumentException("Invalid value for expirationMonth. Must be greater than or equal to 1.");
    }
    if (expirationMonth != null && expirationMonth > 12) {
      throw new IllegalArgumentException("Invalid value for expirationMonth. Must be less than or equal to 12.");
    }
    
    
    this.expirationMonth = expirationMonth;
    return this;
  }

   /**
   * Expiration month
   * minimum: 1
   * maximum: 12
   * @return expirationMonth
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Expiration month")

  public Integer getExpirationMonth() {
    return expirationMonth;
  }


  public void setExpirationMonth(Integer expirationMonth) {
    if (expirationMonth != null && expirationMonth < 1) {
      throw new IllegalArgumentException("Invalid value for expirationMonth. Must be greater than or equal to 1.");
    }
    if (expirationMonth != null && expirationMonth > 12) {
      throw new IllegalArgumentException("Invalid value for expirationMonth. Must be less than or equal to 12.");
    }
    
    this.expirationMonth = expirationMonth;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PayToolsApiModelsCardBaseWithSecurityCode instance itself
   */
  public PayToolsApiModelsCardBaseWithSecurityCode putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayToolsApiModelsCardBaseWithSecurityCode payToolsApiModelsCardBaseWithSecurityCode = (PayToolsApiModelsCardBaseWithSecurityCode) o;
    return Objects.equals(this.cvv, payToolsApiModelsCardBaseWithSecurityCode.cvv) &&
        Objects.equals(this.cardNumber, payToolsApiModelsCardBaseWithSecurityCode.cardNumber) &&
        Objects.equals(this.expirationYear, payToolsApiModelsCardBaseWithSecurityCode.expirationYear) &&
        Objects.equals(this.expirationMonth, payToolsApiModelsCardBaseWithSecurityCode.expirationMonth)&&
        Objects.equals(this.additionalProperties, payToolsApiModelsCardBaseWithSecurityCode.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(cvv, cardNumber, expirationYear, expirationMonth, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayToolsApiModelsCardBaseWithSecurityCode {\n");
    sb.append("    cvv: ").append(toIndentedString(cvv)).append("\n");
    sb.append("    cardNumber: ").append(toIndentedString(cardNumber)).append("\n");
    sb.append("    expirationYear: ").append(toIndentedString(expirationYear)).append("\n");
    sb.append("    expirationMonth: ").append(toIndentedString(expirationMonth)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cvv");
    openapiFields.add("cardNumber");
    openapiFields.add("expirationYear");
    openapiFields.add("expirationMonth");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("cardNumber");
    openapiRequiredFields.add("expirationYear");
    openapiRequiredFields.add("expirationMonth");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PayToolsApiModelsCardBaseWithSecurityCode
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PayToolsApiModelsCardBaseWithSecurityCode.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PayToolsApiModelsCardBaseWithSecurityCode is not found in the empty JSON string", PayToolsApiModelsCardBaseWithSecurityCode.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PayToolsApiModelsCardBaseWithSecurityCode.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("cvv").isJsonNull() && (jsonObj.get("cvv") != null && !jsonObj.get("cvv").isJsonNull()) && !jsonObj.get("cvv").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cvv` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cvv").toString()));
      }
      if (!jsonObj.get("cardNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cardNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cardNumber").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PayToolsApiModelsCardBaseWithSecurityCode.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PayToolsApiModelsCardBaseWithSecurityCode' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PayToolsApiModelsCardBaseWithSecurityCode> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PayToolsApiModelsCardBaseWithSecurityCode.class));

       return (TypeAdapter<T>) new TypeAdapter<PayToolsApiModelsCardBaseWithSecurityCode>() {
           @Override
           public void write(JsonWriter out, PayToolsApiModelsCardBaseWithSecurityCode value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PayToolsApiModelsCardBaseWithSecurityCode read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PayToolsApiModelsCardBaseWithSecurityCode instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PayToolsApiModelsCardBaseWithSecurityCode given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PayToolsApiModelsCardBaseWithSecurityCode
  * @throws IOException if the JSON string is invalid with respect to PayToolsApiModelsCardBaseWithSecurityCode
  */
  public static PayToolsApiModelsCardBaseWithSecurityCode fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PayToolsApiModelsCardBaseWithSecurityCode.class);
  }

 /**
  * Convert an instance of PayToolsApiModelsCardBaseWithSecurityCode to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

