/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Tokenization Action
 */
@JsonAdapter(PayToolsBlAuthenticationTokenizationAction.Adapter.class)public enum PayToolsBlAuthenticationTokenizationAction {
  
  ALWAYS("Always"),
  
  IFCHARGESUCCESSFUL("IfChargeSuccessful"),
  
  NEVER("Never");

  private String value;

  PayToolsBlAuthenticationTokenizationAction(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PayToolsBlAuthenticationTokenizationAction fromValue(String value) {
    for (PayToolsBlAuthenticationTokenizationAction b : PayToolsBlAuthenticationTokenizationAction.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PayToolsBlAuthenticationTokenizationAction> {
    @Override
    public void write(final JsonWriter jsonWriter, final PayToolsBlAuthenticationTokenizationAction enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PayToolsBlAuthenticationTokenizationAction read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PayToolsBlAuthenticationTokenizationAction.fromValue(value);
    }
  }
}

