/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PaymentsCardTypes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Base model for card with Card holder name and Card Type
 */
@ApiModel(description = "Base model for card with Card holder name and Card Type")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PayToolsSharedModelsCardStoredCard {
  public static final String SERIALIZED_NAME_CARD_TOKEN = "cardToken";
  @SerializedName(SERIALIZED_NAME_CARD_TOKEN)
  private String cardToken;

  public static final String SERIALIZED_NAME_EXPIRATION_YEAR = "expirationYear";
  @SerializedName(SERIALIZED_NAME_EXPIRATION_YEAR)
  private Integer expirationYear;

  public static final String SERIALIZED_NAME_EXPIRATION_MONTH = "expirationMonth";
  @SerializedName(SERIALIZED_NAME_EXPIRATION_MONTH)
  private Integer expirationMonth;

  public static final String SERIALIZED_NAME_CARD_TYPE = "cardType";
  @SerializedName(SERIALIZED_NAME_CARD_TYPE)
  private PaymentsCardTypes cardType;

  public static final String SERIALIZED_NAME_CARD_HOLDER_NAME = "cardHolderName";
  @SerializedName(SERIALIZED_NAME_CARD_HOLDER_NAME)
  private String cardHolderName;

  public PayToolsSharedModelsCardStoredCard() {
  }

  public PayToolsSharedModelsCardStoredCard cardToken(String cardToken) {
    
    
    if (cardToken != null && cardToken.length() < 1) {
      throw new IllegalArgumentException("Invalid value for cardToken. Length must be greater than or equal to 1.");
    }
    
    this.cardToken = cardToken;
    return this;
  }

   /**
   * a Reference to a Tokenized string. A Token should be referenced in the format @TOKEN, e.g \&quot;@nQGywsQE9gbURtrXEjTZwtWqeMdK9nsO\&quot;
   * @return cardToken
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "a Reference to a Tokenized string. A Token should be referenced in the format @TOKEN, e.g \"@nQGywsQE9gbURtrXEjTZwtWqeMdK9nsO\"")

  public String getCardToken() {
    return cardToken;
  }


  public void setCardToken(String cardToken) {
    
    
    if (cardToken != null && cardToken.length() < 1) {
      throw new IllegalArgumentException("Invalid value for cardToken. Length must be greater than or equal to 1.");
    }
    this.cardToken = cardToken;
  }


  public PayToolsSharedModelsCardStoredCard expirationYear(Integer expirationYear) {
    if (expirationYear != null && expirationYear < 2023) {
      throw new IllegalArgumentException("Invalid value for expirationYear. Must be greater than or equal to 2023.");
    }
    if (expirationYear != null && expirationYear > 2050) {
      throw new IllegalArgumentException("Invalid value for expirationYear. Must be less than or equal to 2050.");
    }
    
    
    this.expirationYear = expirationYear;
    return this;
  }

   /**
   * Expiration year
   * minimum: 2023
   * maximum: 2050
   * @return expirationYear
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Expiration year")

  public Integer getExpirationYear() {
    return expirationYear;
  }


  public void setExpirationYear(Integer expirationYear) {
    if (expirationYear != null && expirationYear < 2023) {
      throw new IllegalArgumentException("Invalid value for expirationYear. Must be greater than or equal to 2023.");
    }
    if (expirationYear != null && expirationYear > 2050) {
      throw new IllegalArgumentException("Invalid value for expirationYear. Must be less than or equal to 2050.");
    }
    
    this.expirationYear = expirationYear;
  }


  public PayToolsSharedModelsCardStoredCard expirationMonth(Integer expirationMonth) {
    if (expirationMonth != null && expirationMonth < 1) {
      throw new IllegalArgumentException("Invalid value for expirationMonth. Must be greater than or equal to 1.");
    }
    if (expirationMonth != null && expirationMonth > 12) {
      throw new IllegalArgumentException("Invalid value for expirationMonth. Must be less than or equal to 12.");
    }
    
    
    this.expirationMonth = expirationMonth;
    return this;
  }

   /**
   * Expiration year
   * minimum: 1
   * maximum: 12
   * @return expirationMonth
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Expiration year")

  public Integer getExpirationMonth() {
    return expirationMonth;
  }


  public void setExpirationMonth(Integer expirationMonth) {
    if (expirationMonth != null && expirationMonth < 1) {
      throw new IllegalArgumentException("Invalid value for expirationMonth. Must be greater than or equal to 1.");
    }
    if (expirationMonth != null && expirationMonth > 12) {
      throw new IllegalArgumentException("Invalid value for expirationMonth. Must be less than or equal to 12.");
    }
    
    this.expirationMonth = expirationMonth;
  }


  public PayToolsSharedModelsCardStoredCard cardType(PaymentsCardTypes cardType) {
    
    
    
    
    this.cardType = cardType;
    return this;
  }

   /**
   * Get cardType
   * @return cardType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PaymentsCardTypes getCardType() {
    return cardType;
  }


  public void setCardType(PaymentsCardTypes cardType) {
    
    
    
    this.cardType = cardType;
  }


  public PayToolsSharedModelsCardStoredCard cardHolderName(String cardHolderName) {
    
    
    if (cardHolderName != null && cardHolderName.length() < 3) {
      throw new IllegalArgumentException("Invalid value for cardHolderName. Length must be greater than or equal to 3.");
    }
    
    this.cardHolderName = cardHolderName;
    return this;
  }

   /**
   * Cardholder name (as apears on card)
   * @return cardHolderName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Cardholder name (as apears on card)")

  public String getCardHolderName() {
    return cardHolderName;
  }


  public void setCardHolderName(String cardHolderName) {
    
    
    if (cardHolderName != null && cardHolderName.length() < 3) {
      throw new IllegalArgumentException("Invalid value for cardHolderName. Length must be greater than or equal to 3.");
    }
    this.cardHolderName = cardHolderName;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PayToolsSharedModelsCardStoredCard instance itself
   */
  public PayToolsSharedModelsCardStoredCard putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayToolsSharedModelsCardStoredCard payToolsSharedModelsCardStoredCard = (PayToolsSharedModelsCardStoredCard) o;
    return Objects.equals(this.cardToken, payToolsSharedModelsCardStoredCard.cardToken) &&
        Objects.equals(this.expirationYear, payToolsSharedModelsCardStoredCard.expirationYear) &&
        Objects.equals(this.expirationMonth, payToolsSharedModelsCardStoredCard.expirationMonth) &&
        Objects.equals(this.cardType, payToolsSharedModelsCardStoredCard.cardType) &&
        Objects.equals(this.cardHolderName, payToolsSharedModelsCardStoredCard.cardHolderName)&&
        Objects.equals(this.additionalProperties, payToolsSharedModelsCardStoredCard.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardToken, expirationYear, expirationMonth, cardType, cardHolderName, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayToolsSharedModelsCardStoredCard {\n");
    sb.append("    cardToken: ").append(toIndentedString(cardToken)).append("\n");
    sb.append("    expirationYear: ").append(toIndentedString(expirationYear)).append("\n");
    sb.append("    expirationMonth: ").append(toIndentedString(expirationMonth)).append("\n");
    sb.append("    cardType: ").append(toIndentedString(cardType)).append("\n");
    sb.append("    cardHolderName: ").append(toIndentedString(cardHolderName)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cardToken");
    openapiFields.add("expirationYear");
    openapiFields.add("expirationMonth");
    openapiFields.add("cardType");
    openapiFields.add("cardHolderName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("cardToken");
    openapiRequiredFields.add("expirationYear");
    openapiRequiredFields.add("expirationMonth");
    openapiRequiredFields.add("cardHolderName");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PayToolsSharedModelsCardStoredCard
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PayToolsSharedModelsCardStoredCard.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PayToolsSharedModelsCardStoredCard is not found in the empty JSON string", PayToolsSharedModelsCardStoredCard.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PayToolsSharedModelsCardStoredCard.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("cardToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cardToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cardToken").toString()));
      }
      if (!jsonObj.get("cardHolderName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cardHolderName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cardHolderName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PayToolsSharedModelsCardStoredCard.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PayToolsSharedModelsCardStoredCard' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PayToolsSharedModelsCardStoredCard> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PayToolsSharedModelsCardStoredCard.class));

       return (TypeAdapter<T>) new TypeAdapter<PayToolsSharedModelsCardStoredCard>() {
           @Override
           public void write(JsonWriter out, PayToolsSharedModelsCardStoredCard value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PayToolsSharedModelsCardStoredCard read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PayToolsSharedModelsCardStoredCard instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PayToolsSharedModelsCardStoredCard given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PayToolsSharedModelsCardStoredCard
  * @throws IOException if the JSON string is invalid with respect to PayToolsSharedModelsCardStoredCard
  */
  public static PayToolsSharedModelsCardStoredCard fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PayToolsSharedModelsCardStoredCard.class);
  }

 /**
  * Convert an instance of PayToolsSharedModelsCardStoredCard to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

