/*
 * Orchestra API
 * Code Version 1.0.7.15
 *
 * The version of the OpenAPI document: Prod
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Model for Payment Gateway Description
 */
@ApiModel(description = "Model for Payment Gateway Description")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PayToolsApiModelsPaymentGatewayDescriptionModel {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_PAYMENT_GATEWAY_URL = "paymentGatewayUrl";
  @SerializedName(SERIALIZED_NAME_PAYMENT_GATEWAY_URL)
  private String paymentGatewayUrl;

  public static final String SERIALIZED_NAME_CREDENTIALS_NAMES = "credentialsNames";
  @SerializedName(SERIALIZED_NAME_CREDENTIALS_NAMES)
  private List<String> credentialsNames = null;

  public static final String SERIALIZED_NAME_SUPPORTS_NETWORK_TOKEN = "supportsNetworkToken";
  @SerializedName(SERIALIZED_NAME_SUPPORTS_NETWORK_TOKEN)
  private Boolean supportsNetworkToken;

  public PayToolsApiModelsPaymentGatewayDescriptionModel() {
  }

  public PayToolsApiModelsPaymentGatewayDescriptionModel description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * Payment Gateway Description (informational)
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Payment Gateway Description (informational)")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public PayToolsApiModelsPaymentGatewayDescriptionModel name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * The ePayTools internal identifier for this Payment Gateway
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ePayTools internal identifier for this Payment Gateway")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public PayToolsApiModelsPaymentGatewayDescriptionModel displayName(String displayName) {
    
    
    
    
    this.displayName = displayName;
    return this;
  }

   /**
   * The name of the Payment Gateway in friendly format
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the Payment Gateway in friendly format")

  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    
    
    
    this.displayName = displayName;
  }


  public PayToolsApiModelsPaymentGatewayDescriptionModel paymentGatewayUrl(String paymentGatewayUrl) {
    
    
    
    
    this.paymentGatewayUrl = paymentGatewayUrl;
    return this;
  }

   /**
   * Url to Payment Gateway site (informational)
   * @return paymentGatewayUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Url to Payment Gateway site (informational)")

  public String getPaymentGatewayUrl() {
    return paymentGatewayUrl;
  }


  public void setPaymentGatewayUrl(String paymentGatewayUrl) {
    
    
    
    this.paymentGatewayUrl = paymentGatewayUrl;
  }


  public PayToolsApiModelsPaymentGatewayDescriptionModel credentialsNames(List<String> credentialsNames) {
    
    
    
    
    this.credentialsNames = credentialsNames;
    return this;
  }

  public PayToolsApiModelsPaymentGatewayDescriptionModel addCredentialsNamesItem(String credentialsNamesItem) {
    if (this.credentialsNames == null) {
      this.credentialsNames = new ArrayList<>();
    }
    this.credentialsNames.add(credentialsNamesItem);
    return this;
  }

   /**
   * A list of all credential parameters needed to provide for this Payment Gateway
   * @return credentialsNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of all credential parameters needed to provide for this Payment Gateway")

  public List<String> getCredentialsNames() {
    return credentialsNames;
  }


  public void setCredentialsNames(List<String> credentialsNames) {
    
    
    
    this.credentialsNames = credentialsNames;
  }


  public PayToolsApiModelsPaymentGatewayDescriptionModel supportsNetworkToken(Boolean supportsNetworkToken) {
    
    
    
    
    this.supportsNetworkToken = supportsNetworkToken;
    return this;
  }

   /**
   * Indicates whether the Payment gateway supports Network Token (from Card schemes)
   * @return supportsNetworkToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether the Payment gateway supports Network Token (from Card schemes)")

  public Boolean getSupportsNetworkToken() {
    return supportsNetworkToken;
  }


  public void setSupportsNetworkToken(Boolean supportsNetworkToken) {
    
    
    
    this.supportsNetworkToken = supportsNetworkToken;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PayToolsApiModelsPaymentGatewayDescriptionModel instance itself
   */
  public PayToolsApiModelsPaymentGatewayDescriptionModel putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayToolsApiModelsPaymentGatewayDescriptionModel payToolsApiModelsPaymentGatewayDescriptionModel = (PayToolsApiModelsPaymentGatewayDescriptionModel) o;
    return Objects.equals(this.description, payToolsApiModelsPaymentGatewayDescriptionModel.description) &&
        Objects.equals(this.name, payToolsApiModelsPaymentGatewayDescriptionModel.name) &&
        Objects.equals(this.displayName, payToolsApiModelsPaymentGatewayDescriptionModel.displayName) &&
        Objects.equals(this.paymentGatewayUrl, payToolsApiModelsPaymentGatewayDescriptionModel.paymentGatewayUrl) &&
        Objects.equals(this.credentialsNames, payToolsApiModelsPaymentGatewayDescriptionModel.credentialsNames) &&
        Objects.equals(this.supportsNetworkToken, payToolsApiModelsPaymentGatewayDescriptionModel.supportsNetworkToken)&&
        Objects.equals(this.additionalProperties, payToolsApiModelsPaymentGatewayDescriptionModel.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, name, displayName, paymentGatewayUrl, credentialsNames, supportsNetworkToken, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayToolsApiModelsPaymentGatewayDescriptionModel {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    paymentGatewayUrl: ").append(toIndentedString(paymentGatewayUrl)).append("\n");
    sb.append("    credentialsNames: ").append(toIndentedString(credentialsNames)).append("\n");
    sb.append("    supportsNetworkToken: ").append(toIndentedString(supportsNetworkToken)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("name");
    openapiFields.add("displayName");
    openapiFields.add("paymentGatewayUrl");
    openapiFields.add("credentialsNames");
    openapiFields.add("supportsNetworkToken");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PayToolsApiModelsPaymentGatewayDescriptionModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PayToolsApiModelsPaymentGatewayDescriptionModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PayToolsApiModelsPaymentGatewayDescriptionModel is not found in the empty JSON string", PayToolsApiModelsPaymentGatewayDescriptionModel.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("description").isJsonNull() && (jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if (!jsonObj.get("name").isJsonNull() && (jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("displayName").isJsonNull() && (jsonObj.get("displayName") != null && !jsonObj.get("displayName").isJsonNull()) && !jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      if (!jsonObj.get("paymentGatewayUrl").isJsonNull() && (jsonObj.get("paymentGatewayUrl") != null && !jsonObj.get("paymentGatewayUrl").isJsonNull()) && !jsonObj.get("paymentGatewayUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paymentGatewayUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentGatewayUrl").toString()));
      }
      // ensure the optional json data is an array if present (nullable)
      if (jsonObj.get("credentialsNames") != null && !jsonObj.get("credentialsNames").isJsonNull() && !jsonObj.get("credentialsNames").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `credentialsNames` to be an array in the JSON string or null but got `%s`", jsonObj.get("credentialsNames").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PayToolsApiModelsPaymentGatewayDescriptionModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PayToolsApiModelsPaymentGatewayDescriptionModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PayToolsApiModelsPaymentGatewayDescriptionModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PayToolsApiModelsPaymentGatewayDescriptionModel.class));

       return (TypeAdapter<T>) new TypeAdapter<PayToolsApiModelsPaymentGatewayDescriptionModel>() {
           @Override
           public void write(JsonWriter out, PayToolsApiModelsPaymentGatewayDescriptionModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PayToolsApiModelsPaymentGatewayDescriptionModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PayToolsApiModelsPaymentGatewayDescriptionModel instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PayToolsApiModelsPaymentGatewayDescriptionModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PayToolsApiModelsPaymentGatewayDescriptionModel
  * @throws IOException if the JSON string is invalid with respect to PayToolsApiModelsPaymentGatewayDescriptionModel
  */
  public static PayToolsApiModelsPaymentGatewayDescriptionModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PayToolsApiModelsPaymentGatewayDescriptionModel.class);
  }

 /**
  * Convert an instance of PayToolsApiModelsPaymentGatewayDescriptionModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

